### ISSUE TITLE
NPM publish?

### ISSUE THREAD

**Issue by sjml** [phosphor-icons/webcomponents#1]
Hi there! Love the icon set, and am already using it in a project by hacking the SVGs directly into my code. I was starting to prep component versions of them when I saw this was already in progress. Is anything in particular preventing this from being published on NPM? Anything you need a hand with to push it over the finish line?

**Comment by rektdeckard** [comment]
Hey, thank so much for the interest, and for the offer! Haven't had a chance to finish it off, but I'd love some contribution! This is really my first foray into web components, so feel free to suggest a better way of doing things if you see one.

**Comment by sjml** [comment]
I haven't tried using this setup yet, but will install direct from the repo and see how it flies. :)

**Comment by rektdeckard** [comment]
If I recall there were some quirks with passing SVG namespaced elements into the `<slot>` but I'll have to take a look again to remember what was up with that. Besides that, I think it's pretty close. Will try to get to it this weekend.

**Comment by rektdeckard** [comment]
Also would like to set it up for code-splitting.

**Comment by rektdeckard** [comment]
After a little digging today, I'd say the only thing really missing is library-supported tree shaking, since it seems the web components spec does not support slotted SVG-namespaced elements. In light of that, I think I'm going to hit publish and deal with that later...

**Comment by SebastianGarces** [comment]
Hi there, any update on this? :)

**Comment by rektdeckard** [comment]
Package has finally been published at long last 😅 [@phosphor-icons/webcomponents](https://www.npmjs.com/package/@phosphor-icons/webcomponents) 
Feedback welcome, as I'm not too up on the Web Components ecosystem.

**Comment by aarongerig** [comment]
@rektdeckard Thank you for your work! Phosphor Icons as a library looks very promising and we are planning to use it for our new website. There we'd like to integrate the icons as web components, so I can definitely give you some feedback on that, once we start working on the integration (Q3/Q4 of 2023).
